### PR TITLE
Fix edge case when using specific specops in Converter

### PR DESCRIPTION
**Pull request by avitalsh**
Following slack discussion with @jvmancuso:
Fixed bug in ```find_output_names``` - the problem was that it was searching for names in the trimmed_pb instead of the entire graph. This was not working for a model of the type - 
```
x1, x2 = ChannelSplit()(input_img) #tf.split wrapped as keras layer
x = tf.keras.layers.Conv2D(6, (2,2), use_bias=True, padding='same')(x1)
x = tf.keras.layers.Concatenate(axis=-1)([x2, x])
```
The first output of split was an input to the conv node which is removed in trimmed_pb, and therefore was not found.

This was fixed by searching the original graphdef instead of the trimmed one.

Another change in ```find_output_names``` was to insert the names by their order and not by the order of apperance in the graph. This caused bugs when the second output was used before the first, due to 
https://github.com/tf-encrypted/tf-encrypted/blob/92722ba13c9f536066e6269341ec8963041caef5/tf_encrypted/convert/convert.py#L132-L133

### CODE REVIEW

**Comment by jvmancuso** [comment]
CI should be able to pass for this once we pull changes from master!

**Comment by mortendahl** [comment]
this looks good to me; @jvmancuso any comments?

**Comment by mortendahl** [comment]
any thoughts on what could be tested for @jvmancuso ?

**Comment by jvmancuso** [comment]
I'm thinking a minimal example that reproduces the bug on master. A slimmed down version of the original code that caused this issue would work as well

**Comment by avitalsh** [comment]
@jvmancuso test was added

**Pull request merged**
