### PR TITLE
Fix for TF v1.14.0-rc0

### LINKED ISSUE #526: 'base_layer_utils' has no attribute 'unique_layer_name'
AttributeError: module 'tensorflow.python.keras.engine.base_layer_utils' has no attribute 'unique_layer_name'.

Happened on TF 1.14.0rc0.

### PR DESCRIPTION
**Pull request by jvmancuso**
Fixes #526 

Previously, we were using `unique_layer_name` from tf.keras.engine.base_layer_utils, however in TensorFlow >1.13.0 this function was renamed to `unique_object_name` and moved to tf.keras.backend.py.  I've copied the function logic over, since it luckily only relies on common Python libraries and public TensorFlow functions (specifically, `tf.get_default_graph()`).

### CODE REVIEW

**Comment by yanndupis** [comment]
@jvmancuso, looks great. If @mortendahl is ok I think., we can approve it. 

I have re-run the pysyft notebooks with this fix installed and TF 1.14.0-rc and it works. 

However I have noticed that I am getting the insecure randomness warning with this version of TF #513

```
WARNING: Logging before flag parsing goes to stderr.
W0605 12:49:04.146198 4654921152 secure_random.py:22] Falling back to insecure randomness since the required custom op could not be found for the installed version of TensorFlow (1.14.0-rc0). Fix this by compiling custom ops.
```

**Comment by justin1121** [comment]
Yep there is work we need to do to be able to support other versions of tensorflow for secure numbers.

**Comment by jvmancuso** [comment]
Cool, tagging #513 so there's a link back to this note in the relevant open issue

**Comment by mortendahl** [comment]
it looks good, but one question: what are they doing in tf.keras if this function is gone? are we, or should we, be doing the same instead of using this older behaviour?

**Comment by jvmancuso** [comment]
The behavior is identical: the only thing that's changed is the function name and it's location insider the TF codebase

**Pull request merged**
