### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by mortendahl**

### CODE REVIEW

**Comment by ianlivingstone** [comment]
We should add or promote a section on how to become a contributor.

**Comment by ianlivingstone** [comment]
It'd be nice if there was an explicit community call out for how they can join / participate!

**Comment by mortendahl** [comment]
anything concrete in mind @ianlivingstone?

**Comment by mortendahl** [comment]
i'll merge this guy up, we can open another issue/PR for the remaining!

**Pull request merged**
